//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViaroAPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class alumn
    {
        public alumn()
        {
            this.course_alumn = new HashSet<course_alumn>();
        }

        public int id_alumn { get; set; }
        [Required(ErrorMessage = "El campo Nombres No puede ser Vacio.")]
        [StringLength(50)]
        public string first_name { get; set; }
        [Required(ErrorMessage = "El campo Apellidos No puede ser Vacio.")]
        [StringLength(60)]
        public string last_name { get; set; }
        [StringLength(1)]
        [RegularExpression("^M|F$")]
        public string gender { get; set; }
        [Required(ErrorMessage = "El campo Fecha de Nacimiento No puede ser Vacio.")]
        public Nullable<System.DateTime> bith_date { get; set; }
    
        public virtual ICollection<course_alumn> course_alumn { get; set; }
    }
}
