//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViaroAPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class course_alumn
    {
        public int id_course_alumn { get; set; }
        public Nullable<int> id_alumn { get; set; }
        public Nullable<int> id_course { get; set; }
        [Required(ErrorMessage = "El campo Seccion No puede ser Vacio.")]
        [StringLength(1)]
        public string section { get; set; }

        public virtual alumn alumn { get; set; }
        public virtual Course Course { get; set; }
    }
}
