//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViaroAPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ViaroAPPEntities : DbContext
    {
        public ViaroAPPEntities()
            : base("name=ViaroAPPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<alumn> alumns { get; set; }
        public DbSet<Course> Courses { get; set; }
        public DbSet<course_alumn> course_alumn { get; set; }
        public DbSet<teacher> teachers { get; set; }
    }
}
