//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViaroAPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class teacher
    {
        public teacher()
        {
            this.Courses = new HashSet<Course>();
        }
    
        public int id_teacher { get; set; }
        [Required(ErrorMessage = "El campo Nombres No puede ser Vacio.")]
        [StringLength(50)]
        public string first_name { get; set; }
        [Required(ErrorMessage = "El campo Apellidos No puede ser Vacio.")]
        [StringLength(60)]
        public string last_name { get; set; }
        [StringLength(1)]
        [RegularExpression("^M|F$")]
        public string gender { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
    }
}
